export const TECHNICAL_MEASUREMENT_FIELD_OPTIONS = [
  { key: "nota_venta", label: "Nota de Venta / NV" },
  { key: "fecha_nota_pedido", label: "Fecha de Nota de Pedido" },
  { key: "fecha", label: "Fecha de medición" },
  { key: "cliente_nombre", label: "Nombre del cliente" },
  { key: "cliente_apellido", label: "Apellido del cliente" },
  { key: "distribuidor", label: "Distribuidor" },
  { key: "tipo_revestimiento_comercial", label: "Tipo revestimiento" },
  { key: "fabricante_revestimiento", label: "Fabricante revestimiento" },
  { key: "lucera", label: "Lucera" },
  { key: "lucera_cantidad", label: "Cant. de luceras" },
  { key: "lucera_posicion", label: "Posición de lucera" },
  { key: "color_revestimiento", label: "Color revestimiento" },
  { key: "color_sistema", label: "Color sistema" },
  { key: "listones", label: "Listones" },
  { key: "puerta", label: "Puerta" },
  { key: "posicion_puerta", label: "Posición de la puerta" },
  { key: "parantes.cant", label: "Parantes cantidad" },
  { key: "parantes.distribucion", label: "Parantes distribución" },
  { key: "pasador_manual", label: "Pasador manual" },
  { key: "instalacion", label: "Instalación" },
  { key: "anclaje", label: "Anclaje" },
  { key: "piernas", label: "Piernas" },
  { key: "rebaje", label: "Rebaje" },
  { key: "rebaje_altura", label: "Altura de rebaje" },
  { key: "rebaje_lateral", label: "Rebaje lateral" },
  { key: "rebaje_inferior", label: "Rebaje inferior" },
  { key: "trampa_tierra", label: "Trampa de tierra" },
  { key: "trampa_tierra_altura", label: "Altura trampa de tierra" },
  { key: "surface_m2", label: "Superficie m2" },
  { key: "budget_width_m", label: "Ancho presupuesto (m)" },
  { key: "budget_height_m", label: "Alto presupuesto (m)" },
  { key: "payment_method", label: "Financiación / forma de pago" },
  { key: "porton_type", label: "Tipo / sistema del presupuesto" },
];
export const TECHNICAL_RULE_OPERATORS = [
  { value: "=", label: "=" },
  { value: "!=", label: "!=" },
  { value: ">", label: ">" },
  { value: ">=", label: ">=" },
  { value: "<", label: "<" },
  { value: "<=", label: "<=" },
  { value: "contains", label: "contiene" },
];
